=== axkg/terminatorX/website/tX.dtd
<!ELEMENT section (linkdb?, (main|bugs|download|screenshots|scratches|links|faq|turntable|aseqjoy|docs|changelog))>
<!ATTLIST section
  name CDATA #REQUIRED>

<!ELEMENT main (general, news)>
<!ELEMENT download (index, current, subsection+)>
<!ELEMENT scratches (para*, scratchtable, para*)>
<!ELEMENT links (subsection)+>
<!ELEMENT faq (qa+)>
<!ELEMENT turntable (para*, turntabletable, para*)>
<!ELEMENT aseqjoy (para*)>
<!ELEMENT docs (para*)>
<!ELEMENT bugs (subsection)+>
<!ELEMENT screenshots (subsection)+>
<!ELEMENT changelog (version+)>

<!ELEMENT linkdb (dlink*)>
<!ELEMENT dlink EMPTY>
<!ATTLIST dlink
  id CDATA #REQUIRED
  url CDATA #REQUIRED
  text CDATA #REQUIRED>
<!ENTITY db SYSTEM "linkdb.xml">

<!ELEMENT scratchtable (scratch)*>
<!ELEMENT scratch (mp3file, author, comment)>
<!ELEMENT mp3file (file, filesize)>
<!ELEMENT filesize (#PCDATA)>
<!ELEMENT author (person, tinycomment?)>
<!ELEMENT comment (nopara, tinycomment?)>

<!ELEMENT turntabletable (tt)*>
<!ELEMENT tt (author, text, ttimages)>
<!ATTLIST tt 
  title CDATA #REQUIRED>
<!ELEMENT ttimages (image+)>
  
<!ELEMENT tinycomment (nopara)>

<!ELEMENT qa (question, answer)>
<!ELEMENT question (#PCDATA)>
<!ELEMENT answer (para+)>

<!ELEMENT index (title)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT subsection (title, (para | tarfiles | rpmfiles | currentversion | file | filelist | ilink)*)>

<!ELEMENT ilink (banner?, (dblink | link), para*)>
<!ELEMENT banner EMPTY>
<!ATTLIST banner
  filename CDATA #REQUIRED>

<!ELEMENT current EMPTY>
<!ATTLIST current
  version CDATA #REQUIRED
  havebz2 (yes|no) "no">
  
<!ELEMENT tarfiles (tar+)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT tar EMPTY>
<!ATTLIST tar
  version CDATA #REQUIRED
  havebz2 (yes|no) "no">

<!ELEMENT currentversion EMPTY>

<!ELEMENT filelist (file)+>
<!ELEMENT rpmfiles (rpm+)>
<!ELEMENT rpm EMPTY>
<!ATTLIST rpm
  version CDATA #REQUIRED
  rpmsubversion CDATA #REQUIRED
  type (src|i386|i586|sparc) #REQUIRED
  distribution CDATA #IMPLIED
  note CDATA #IMPLIED
  ext CDATA #IMPLIED>

<!ELEMENT general (heading, subtitle, text)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT subtitle (nopara)>

<!ELEMENT news (newsitem)*>
<!ELEMENT newsitem (newsheader, newstext)>
<!ELEMENT newsheader ( #PCDATA | link | dblink )*>
<!ELEMENT newstext (para)+>
<!ATTLIST newsheader
  date CDATA #REQUIRED>
  
<!ELEMENT text (para)*>

<!ELEMENT nopara (#PCDATA|screen|bold|red|italic|link|dblink|screenshot|person|itemizedlist|newline|file)*>
<!ELEMENT para (#PCDATA|screen|bold|red|italic|link|dblink|screenshot|person|itemizedlist|newline|file)*>

<!ATTLIST para
  class (fancy|plain) 'fancy'>
  
<!ELEMENT bold (#PCDATA)>
<!ELEMENT screen (#PCDATA)>
<!ELEMENT italic (#PCDATA)>
<!ELEMENT red (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
  ref CDATA #REQUIRED>
  
<!ELEMENT dblink (#PCDATA)>
<!ATTLIST dblink
  id CDATA #REQUIRED>


<!ELEMENT itemizedlist (listitem+)>
<!ELEMENT listitem (nopara|para)+>
<!ELEMENT newline EMPTY>

<!ELEMENT screenshot (nopara)>
<!ATTLIST screenshot
  filename CDATA #REQUIRED>

<!ELEMENT image (nopara)>
<!ATTLIST image
  filename CDATA #REQUIRED>


<!ELEMENT person (name, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT version (listitem+)>
<!ATTLIST version
  name CDATA #REQUIRED
  unreleased CDATA 'false'>

=== axkg/terminatorX/website/changelog.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE section SYSTEM "./tX.dtd">
<section name="changelog">
<changelog>
	<version name="0.5">
		<listitem><para></para></listitem>
	</version>
	<version name="0.5">
		<listitem><para></para></listitem>
	</version>
	<version name="0.5">
		<listitem><para></para></listitem>
	</version>
	<version name="0.5">
		<listitem><para></para></listitem>
	</version>
	<version name="2.2">
		<listitem><para>first released version</para></listitem>
		<listitem><para>added colors, more standard use of X11</para></listitem>
		<listitem><para>added loop support</para></listitem>
		<listitem><para>added statusbar with mode/status display</para></listitem>
		<listitem><para>added commandline options and help (on usage and keys)</para></listitem>
		<listitem><para>added raw/mixed save scratch feature</para></listitem>
		<listitem><para>added licmak to include license into binary</para></listitem>
		<listitem><para>new handling of XAutoRepeat, only turned off now when SPACE pressed</para></listitem>
		<listitem><para>modified wave display (faster + nicer + incorrect (who cares anyway))</para></listitem>
		<listitem><para>Makefile fixed by <person><name>Adrian Reber</name><email>adrian@lisas.de</email></person></para></listitem>
		<listitem><para>bug fixes</para></listitem>
	</version>
	<version name="2.1" unreleased="true">
		<listitem><para>added recording, playback of recording functionality</para></listitem>
	</version>
	<version name="2.0" unreleased="true">
		<listitem><para>moved from multithreaded to singlethreaded</para></listitem>
		<listitem><para>position feedback</para></listitem>
		<listitem><para>bug fixes</para></listitem>
	</version>
	<version name="1.0" unreleased="true">
		<listitem><para>mouse support</para></listitem>
		<listitem><para>no more position display due to pthread/X probs</para></listitem>
		<listitem><para>bug fixes</para></listitem>
	</version>
	<version name="0.5" unreleased="true">
		<listitem><para>first version</para></listitem>
		<listitem><para>no mouse handling</para></listitem>
		<listitem><para>accelerating vtt via sinus</para></listitem>
		<listitem><para>multithreaded</para></listitem>
		<listitem><para>sound aliasing</para></listitem>
	</version>
</changelog>
</section>

=== axkg/terminatorX/website/bugs.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE section SYSTEM "./tX.dtd">
<section name="bugs"> &db; <bugs>
    <subsection>
      <title>Bug Tracking</title>
      <para> To improve bug tracking for terminatorX I've setup a <link
        ref="http://www.bugzilla.org">bugzilla</link> installation on this machine. You can access
        this bugzilla <dblink id="bug42">here</dblink>. </para>
      <para> So if you find a bug in terminatorX or have a feature request please use this
        system so the issue can be handled properly. </para>
      <para> Of course you can also 
        <link ref="http://www-stud.fht-esslingen.de/bugzilla/query.cgi?product=terminatorX">check</link> whether your bug has been
        filed already. </para>
    </subsection>
    <subsection>
      <title>Access</title>
      <para> If you haven't used this bugzilla before you will have to get an <link
        ref="http://www-stud.fht-esslingen.de/bugzilla/createaccount.cgi">account</link>
        if you want to be able to file new bugs. </para>
    </subsection>
  </bugs>
</section>

=== axkg/terminatorX/website/turntable.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE section SYSTEM "./tX.dtd">
<section name="turntable gallery"> &db; <turntable>
    <para>While scratching with the mouse usually <italic>sounds</italic> the way terminatorX users
      want it to (at least if the feedback I get is representative) it doesn't really
      <italic>feel</italic> like scratching. The only way to get that traditional haptic feedback is
      to turn your turntable into a mouse device.</para>
    <para>If you want to do this without harming your mouse nor turntable, the method suggested by
      the terminatorX logo should be feasible. Optical input devices are known to produce best
      results in such a scenario. For those interested here's a <dblink
      id="oldtable">document</dblink> on how I turned my old turntable into a terminatorX device.</para>
    <para>Luckily a lot of terminatorX users have built their own turntables and I'm really happy to
      present some of these creations below. Please, if <italic>your</italic> turntable is missing
        <link ref="mailto:alex@lisas.de">send</link> me some pictures of it so I can add them here.
      <bold>Thanks</bold> to all contributors!</para>
    <turntabletable>
      <tt title="Adam's turntable">
        <author>
          <person>
            <name>Adam King</name>
            <email>aking@lgh.com.au</email>
          </person>
        </author>
        <text>
          <para>Adam's turntable features very unique colors. Not a single feature of the
	  mouse is left unused with this device: All buttons are available and the 2nd axis
	  can be controlled with the red knob.</para>
	  <para>For more details checkout Adam's <link ref="http://members.optusnet.com.au/adamjking/ttable.htm">website</link></para>
        </text>
        <ttimages>
          <image filename="adam1.jpg">
            <nopara>Those colors just rock</nopara>
          </image>
          <image filename="adam2.jpg">
            <nopara>Utlizes the mouse buttons</nopara>
          </image>
          <image filename="adam3.jpg">
            <nopara>From above</nopara>
          </image>
          <image filename="adam4.jpg">
            <nopara>Inside the box</nopara>
          </image>
          <image filename="adam5.jpg">
            <nopara>Smooth mouse integration</nopara>
          </image>
        </ttimages>
      </tt>
      <tt title="Bob's turntable">
        <author>
          <person>
            <name>Bob Arctor</name>
            <email>curious@pb194.luban.sdi.tpnet.pl</email>
          </person>
        </author>
        <text>
          <para>Bob's very interesting turntable transfers it&apos;s rotational speed via a belt.</para><para>He describes
	  his terminatorX device this way: <italic>&quot;The method is especially good for mixing, not only scratching, 
	  because it is very stable (belt eliminates vinyl imperfections, transferring only rotational speed)&quot;</italic></para>
        </text>
        <ttimages>
          <image filename="bob1.jpg">
            <nopara>Belt-driven</nopara>
          </image>
          <image filename="bob2.jpg">
            <nopara>Vinyl look and feel</nopara>
          </image>
          <image filename="bob3.jpg">
            <nopara>Mouse connection</nopara>
          </image>
          <image filename="bob4.jpg">
            <nopara>Works with different turntables</nopara>
          </image>
          <image filename="bob5.jpg">
            <nopara>Complete setup</nopara>
          </image>
          <image filename="bob6.jpg">
            <nopara>The belt</nopara>
          </image>
        </ttimages>
      </tt>      
      <tt title="Fernando's turntable">
        <author>
          <person>
            <name>Fernando S. Fabreti</name>
            <email>ffabreti@yahoo.com.br</email>
          </person>
        </author>
        <text>
          <para>Fernando's turntable differs from the others in this section as he attached the
            mouse to the tone arm of the turntable. Take a look at the &quot;in detail&quot; picture
            to find out how Fernando's table works.</para>
          <para>
            <italic>Note</italic>: Fernando also contributed a scratch - see <dblink
              id="scratches">users' scratches-section</dblink>.</para>
        </text>
        <ttimages>
          <image filename="fernando1.jpg">
            <nopara>The whole thing</nopara>
          </image>
          <image filename="fernando2.jpg">
            <nopara>A little closer</nopara>
          </image>
          <image filename="fernando3.jpg">
            <nopara>Even closer</nopara>
          </image>
          <image filename="fernando4.jpg">
            <nopara>In detail</nopara>
          </image>
          <image filename="fernando5.jpg">
            <nopara>Fernado in action</nopara>
          </image>
        </ttimages>
      </tt>
      <tt title="Toqer's turntable">
        <author>
          <person>
            <name>Toqer</name>
            <email>toqer@pacbell.net</email>
          </person>
        </author>
        <text>
          <para>Toqer is using an optical device for his turntable. The image is somewhat low-res
            but you get the idea.</para>
        </text>
        <ttimages>
          <image filename="toqer1.jpg">
            <nopara>Toqer's optical turntable</nopara>
          </image>
        </ttimages>
      </tt>
      <tt title="Matt's turntable">
        <author>
          <person>
            <name>Matt Thomas</name>
            <email>loopdloop@jaggedsoft.com</email>
          </person>
        </author>
        <text>
          <para>Proudly presenting DJ Loopdloop's terminatorX turntable. A very interesting approach
            that hides the mouse completely inside the turntable.</para>
          <para>Have a look...</para>
        </text>
        <ttimages>
          <image filename="matt1.jpg">
            <nopara>Could be a &quot;usual&quot; turntable</nopara>
          </image>
          <image filename="matt2.jpg">
            <nopara>But it's not</nopara>
          </image>
          <image filename="matt3.jpg">
            <nopara>Tricky details</nopara>
          </image>
        </ttimages>
      </tt>
      <tt title="My turntable">
        <author>
          <person>
            <name>Me</name>
            <email>alex@lisas.de</email>
          </person>
        </author>
        <text>
          <para>These are the pictures of my very own terminatorX turntable. The turntable is
            described in more detail <dblink id="oldtable">here</dblink>.</para>
        </text>
        <ttimages>
          <image filename="tt_normal.jpg">
            <nopara>The turntable and its connector</nopara>
          </image>
          <image filename="tt_top1.jpg">
            <nopara>Again</nopara>
          </image>
          <image filename="tt_top_zoom.jpg">
            <nopara>The motor</nopara>
          </image>
          <image filename="tt_open_total.jpg">
            <nopara>Turntable's inside</nopara>
          </image>
          <image filename="tt_mouse_axis.jpg">
            <nopara>The axis to connect</nopara>
          </image>
          <image filename="tt_mouse_connect.jpg">
            <nopara>Axis attached to motor</nopara>
          </image>
          <image filename="tt_the_mouse.jpg">
            <nopara>Maximum compatibility ;)</nopara>
          </image>
        </ttimages>
      </tt>
    </turntabletable>
    <para>Your turntable is missing? Please, <link ref="mailto:alex@lisas.de">send</link> me some
      pictures of it so I can add them.</para>
  </turntable>
</section>

=== axkg/terminatorX/website/docs.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE section SYSTEM "./tX.dtd">
<section name='docs'>
  <docs>
    <para>The following documentation is available: 
    <itemizedlist>
      <listitem>
        <para>An HTML version of the 
        <link ref='manual/index.html'>terminatorX online manual</link>. If you
        have GNOME2's 
        <italic>yelp</italic> installed you should be able to read this manual
        by selecting it from the 
        <italic>Help</italic> menu in the termintorX main window.</para>
      </listitem>
      <listitem>
        <para>
        <person>
          <name>Brian</name>
          <email>bredfern@calarts.edu</email>
        </person>wrote a nice 
        <italic>QuickToot</italic> tutorial on terminatorX. Check it out 
        <link ref='tutorial.html'>here</link> or have look at all the other 
        <link ref='http://dcdj.com'>QuickToots</link> available.</para>
      </listitem>
      <listitem>
        <para>If you're stuck on installing terminatorX I recommend having a
        look at the 
        <link ref='INSTALL'>INSTALL</link> file.</para>
      </listitem>
      <listitem>
        <para>I also maintain a 
        <link ref='faq.html'>Frequently Asked Questions</link> document.</para>
      </listitem>
    </itemizedlist></para>
    <para>Additionally there's a 
    <itemizedlist>
      <listitem>
        <para>HTML version of the 
        <link ref='aseqjoy.html'>aseqjoy</link>
        <link ref='aseqjoy-man.html'>man page</link>.</para>
      </listitem>
      <listitem>
        <para>And a rather old 
        <link ref='oldturntable.html'>description</link> on how I turned my
        broken turntable into terminatorX device.</para>
      </listitem>
    </itemizedlist></para>
  </docs>
</section>

=== axkg/terminatorX/website/screenshots.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE section SYSTEM "./tX.dtd"[ ]>
<section name='screenshots'>
  <screenshots>
    <subsection>
      <title>What it looks like...</title>
      <para>Here are some screenshots I took of terminatorX 3.80 in
      action.</para>
      <para>
        <screenshot filename='shot-3.80-1.png'>
          <nopara>This shows terminatorX with the sequencer and live scratching
          in effect.</nopara>
        </screenshot>
        <screenshot filename='shot-3.80-2.png'>
          <nopara>Selecting a 
          <link ref='http://www.ladspa.org'>LADSPA</link> plugin from a 
          <link ref='liblrdf'>liblrdf</link> structured menu.</nopara>
        </screenshot>
        <screenshot filename='shot-3.80-3.png'>
          <nopara>Mapping a parameter to a turntable's axis. This works for 
          <link ref='http://www.ladspa.org'>LADSPA</link> plugins, too.</nopara>
        </screenshot>
        <screenshot filename='shot-3.80-4.png'>
          <nopara>Configuring terminatorX.</nopara>
        </screenshot>
        <screenshot filename='shot-3.80-5'>
          <nopara>Mapping MIDI events to turntable parameters.</nopara>
        </screenshot>
      </para>
    </subsection>
  </screenshots>
</section>

=== axkg/terminatorX/website/faq.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE section SYSTEM "./tX.dtd">
<section name="faq"> &db; <faq>
    <qa>
      <question>What is terminatorX?</question>
      <answer>
        <para>terminatorX is a realtime audio synthesizer that allows you to &quot;scratch&quot; on
          digitally sampled audio data (*.wav, *.au, *.ogg, *.mp3, etc.) the way hiphop-DJs scratch
          on vinyl records. It features multiple turntables, realtime effects (buit-in as well as
            <dblink id="ladspa"/> plugin effects), a sequencer and MIDI interface - all accessible
          through an easy-to-use gtk+ GUI. <bold>This sofware is designed to run under Linux,
            FreeBSD and the like</bold>.</para>
      </answer>
    </qa>
    <qa>
      <question>What does it cost?</question>
      <answer>
        <para>Nothing. TerminatorX is <link ref="http://www.fsf.org/philosophy/free-sw.html">free
          software</link>. Read the <link ref="COPYING">license</link> (GPL V2).</para>
      </answer>
    </qa>
    <qa>
      <question>What platforms does it run on?</question>
      <answer>
        <para>TerminatorX should run on any recent Linux or FreeBSD system. I develop terminatorX on
          an X86-System, but the source contains support for bigendian machines (PowerPC for
          example). If you experience platform related troubles, please let me know.</para>
      </answer>
    </qa>
    <qa>
      <question>What audio quality is supported?</question>
      <answer>
        <para>TerminatorX operates at an arbitrary sampling rate with 16Bit samples and 2 channels
          (aka stereo). Samples will be converted to mono on loading.</para>
      </answer>
    </qa>
    <qa>
      <question>Why does it take terminatorX so long to load samples?</question>
      <answer>
        <para>This depends on the file your loading. Wavfiles are loaded with the builtin wavloading
          routines (if enabled on compiletime) and this happens very fast. For compressed audio
          files the necessary decompression will consume quite some cpu time on loading.</para>
        <para>Since Version 3.73 loading of audiofiles has been significantly accelerated with the
          libaudiofile, libvorbis and mad methods.</para>
      </answer>
    </qa>
    <qa>
      <question>Why doesn't terminatorX support mmap'ed wav reading?</question>
      <answer>
        <para>Oh well due to my laziness I guess. <person>
            <name>Benno Senoner</name>
            <email>sbenno@gardena.net</email>
          </person> wrote a <link
            ref="http://www.gardena.net/benno/linux/terminatorX-3.2-mmap.patch"> patch</link>
          against 3.2 to support &quot;on-the-fly&quot; reading of wavfiles. The problem is the
          patch wasn't applyable to later versions of terminatorX, nor would it work with sox/mpg123
          support. I still plan to port the patch to the newer releases sometime.</para>
      </answer>
    </qa>
    <qa>
      <question>How can I use a second mouse, a joystick or other input devices for scratching?</question>
      <answer>
        <para>
          <bold>Update:</bold> If you want to use your joystick along with your mouse I suggest
          using my tiny <dblink id="aseqjoy"/> tool to connect your joystick to the MIDI input port
          of terminatorX.</para>
        <para>If you want to use another mouse however, you need to configure this mouse as an
          XFree86 XInput devices and from what I've read I assume you'll need to have XFree86
          3.3.3.1 or higher. If you want to know how to do this read your XF86Config manual page
          (run man XF86Config) and find the part on &quot;the optional XInput section&quot;. If you
          successfully configured your second (third ...) mouse / input device for XFree86 you now
          need to turn on XInput-support in the Options-dialog of terminatorX and you have to select
          the XInput device you want terminatorX to initialize. Now either press &quot;Apply&quot;
          or &quot;Ok&quot; and you should be able to scratch with that devices next time you press &quot;Start&quot;.</para>
      </answer>
    </qa>
    <qa>
      <question>Why do I get &quot;./terminatorX: undefined symbol:
        _t24__default_alloc_template2b1i0.free_list&quot; when I run terminatorX?</question>
      <answer>
        <para>You probably downloaded the binary-rpm-package and your libstdc++ is outdated. This
          seems to occur on Mandrake systems only. Upgrading with a newer libstdc++ package should
          fix this.</para>
      </answer>
    </qa>
    <qa>
      <question>Why do I get &quot;tX_seqpar.h:25: list: No such file or directory&quot; when
        building terminatorX myself?</question>
      <answer>
        <para>You don't have the libstdc++ headers installed. Install the libstdc++-devel package
          for the libstdc++-package you have installed.</para>
      </answer>
    </qa>
    <qa>
      <question>What can I do if my mouse doesn't work in scratch mode?</question>
      <answer>
        <para>Now this issue is rather tricky, as it seems a lot of problems can be the reason here,
          but there are some things you can try: <itemizedlist>
            <listitem>
              <nopara>Make sure that your X-Server supports XFree86-DGA. Remove any lines that read</nopara>
              <para>
                <screen>Option &quot;omit xfree86-dga&quot;</screen>
              </para>
              <para>from your <screen>XF86Config</screen>. Check whether the Server loaded dga by
                running <bold>xdpyinfo</bold> - if DGA is loaded one of the lines you get from
                xdpyinfo should read <italic>XFree86-DGA</italic>. To check whether DGA actually
                works run <bold>dga</bold> as root - <red>Warning:</red> the only way to exit this
                tool is pressing 'q' on your keyboard - and it might take some seconds until it reacts.</para>
            </listitem>
            <listitem>
              <nopara>Try running terminatorX as root. This fixes the problem for most people.</nopara>
            </listitem>
          </itemizedlist>
        </para>
        <para>If all this doen't help let me know.</para>
      </answer>
    </qa>
    <qa>
      <question>Should I install terminatorX suid root?</question>
      <answer>
        <para><bold>No</bold>. While I recommended installing terminatorX suid root before - I no 
          longer do for two reasons:
          <itemizedlist>            
            <listitem><nopara>According to this
              <link ref="http://www.securityfocus.com/archive/1/328469">bugtraq posting</link> it is 
              insecure (I've always warned you before). Although this specific exploit is fixable I'm 
              rather sure it would be easy to create others.</nopara></listitem>
            <listitem><nopara>Some machines seem to deadlock with the engine thread
              running with rt-scheduling for no obvious reason. Unluckily this is pretty hard
              to debug.</nopara></listitem>
          </itemizedlist>         
        </para>
        <para>So instead of running terminatorX suid root I recommend using either 
          <link ref="http://www.kernel.org">Linux 2.6.x</link> or
          <person>
            <name>Con Kolivas</name>
            <email>conman@kolivas.org</email>
          </person>' <link ref="http://members.optusnet.com.au/ckolivas/kernel/">patches</link>
          against Linux 2.4.x. With these new scheduler tweaks terminatorX performs very well without
          extra privileges.</para>
        <!--<para>Installing terminatorX <italic>suid root</italic> improves terminatorX' performance
          significantly for non-root users - as terminatorX will use the suid-root privileges to
          create the engine thread with realtime-scheduling-priority. Immediatley after the creation
          of the thread terminatorX drops root privileges before any files or devices are accessed.
          The problem is: the Linux pthreads manager thread can not be told to drop it's root
          privileges, which means that while the two threads executing terminatorX code run with the
          real user's privileges, the pthread manager thread still runs with root-privileges. While
          I cannot see how a malicious user or software could utlize this thread to acquire root
          privileges it might still be possible, so you'll have to make your on decision on
          performance vs security.</para>-->
      </answer>
    </qa>
    <!--<qa>
      <question>How do I install terminatorX suid root?</question>
      <answer>
        <para>As root <italic>cd</italic> into the directory you installed terminatorX to (typically
          that is <italic>/usr/local/bin</italic> or <italic>/usr/bin</italic>) and run the
          following commandline:</para>
        <para>
          <screen>chown root: ./terminatorX &amp;&amp; chmod u+s ./terminatorX</screen>
        </para>
      </answer>
    </qa>-->
    <qa>
      <question>Is there a Windows version of terminatorX?</question>
      <answer>
        <para>No, there is no such version, nor will I port it myself - as I hardly have the time
          to maintain the regular version. If you plan to port it,
          please let <person>
            <name>me</name>
            <email>alex@lisas.de</email>
          </person> 
          know.</para>
      </answer>
    </qa>
    <qa>
      <question>Where does the name come from?</question>
      <answer>
        <para>If you don't know find out a little something about <link
            ref="http://www.publicenemy.com">Public Enemy</link>. Learn who <link
            ref="http://www.publicenemy.com/soldiers/termx.php"> TerminatorX</link> is or <link
            ref="http://www.publicenemy.com/gallery/images/txday.jpg">see him</link>do his work</para>
      </answer>
    </qa>
  </faq>
</section>
