=== axkg/terminatorX/website/tX.dtd
<!ELEMENT section (linkdb?, (main|bugs|download|screenshots|scratches|links|faq|turntable|aseqjoy|docs|changelog))>
<!ATTLIST section
  name CDATA #REQUIRED>

<!ELEMENT main (general, news)>
<!ELEMENT download (index, current, subsection+)>
<!ELEMENT scratches (para*, scratchtable, para*)>
<!ELEMENT links (subsection)+>
<!ELEMENT faq (qa+)>
<!ELEMENT turntable (para*, turntabletable, para*)>
<!ELEMENT aseqjoy (para*)>
<!ELEMENT docs (para*)>
<!ELEMENT bugs (subsection)+>
<!ELEMENT screenshots (subsection)+>
<!ELEMENT changelog (version+)>

<!ELEMENT linkdb (dlink*)>
<!ELEMENT dlink EMPTY>
<!ATTLIST dlink
  id CDATA #REQUIRED
  url CDATA #REQUIRED
  text CDATA #REQUIRED>
<!ENTITY db SYSTEM "linkdb.xml">

<!ELEMENT scratchtable (scratch)*>
<!ELEMENT scratch (mp3file, author, comment)>
<!ELEMENT mp3file (file, filesize)>
<!ELEMENT filesize (#PCDATA)>
<!ELEMENT author (person, tinycomment?)>
<!ELEMENT comment (nopara, tinycomment?)>

<!ELEMENT turntabletable (tt)*>
<!ELEMENT tt (author, text, ttimages)>
<!ATTLIST tt 
  title CDATA #REQUIRED>
<!ELEMENT ttimages (image+)>
  
<!ELEMENT tinycomment (nopara)>

<!ELEMENT qa (question, answer)>
<!ELEMENT question (#PCDATA)>
<!ELEMENT answer (para+)>

<!ELEMENT index (title)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT subsection (title, (para | tarfiles | rpmfiles | currentversion | file | filelist | ilink)*)>

<!ELEMENT ilink (banner?, (dblink | link), para*)>
<!ELEMENT banner EMPTY>
<!ATTLIST banner
  filename CDATA #REQUIRED>

<!ELEMENT current EMPTY>
<!ATTLIST current
  version CDATA #REQUIRED
  havebz2 (yes|no) "no">
  
<!ELEMENT tarfiles (tar+)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT tar EMPTY>
<!ATTLIST tar
  version CDATA #REQUIRED
  havebz2 (yes|no) "no">

<!ELEMENT currentversion EMPTY>

<!ELEMENT filelist (file)+>
<!ELEMENT rpmfiles (rpm+)>
<!ELEMENT rpm EMPTY>
<!ATTLIST rpm
  version CDATA #REQUIRED
  rpmsubversion CDATA #REQUIRED
  type (src|i386|i586|sparc) #REQUIRED
  distribution CDATA #IMPLIED
  note CDATA #IMPLIED
  ext CDATA #IMPLIED>

<!ELEMENT general (heading, subtitle, text)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT subtitle (nopara)>

<!ELEMENT news (newsitem)*>
<!ELEMENT newsitem (newsheader, newstext)>
<!ELEMENT newsheader ( #PCDATA | link | dblink )*>
<!ELEMENT newstext (para)+>
<!ATTLIST newsheader
  date CDATA #REQUIRED>
  
<!ELEMENT text (para)*>

<!ELEMENT nopara (#PCDATA|screen|bold|red|italic|link|dblink|screenshot|person|itemizedlist|newline|file)*>
<!ELEMENT para (#PCDATA|screen|bold|red|italic|link|dblink|screenshot|person|itemizedlist|newline|file)*>

<!ATTLIST para
  class (fancy|plain) 'fancy'>
  
<!ELEMENT bold (#PCDATA)>
<!ELEMENT screen (#PCDATA)>
<!ELEMENT italic (#PCDATA)>
<!ELEMENT red (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
  ref CDATA #REQUIRED>
  
<!ELEMENT dblink (#PCDATA)>
<!ATTLIST dblink
  id CDATA #REQUIRED>


<!ELEMENT itemizedlist (listitem+)>
<!ELEMENT listitem (nopara|para)+>
<!ELEMENT newline EMPTY>

<!ELEMENT screenshot (nopara)>
<!ATTLIST screenshot
  filename CDATA #REQUIRED>

<!ELEMENT image (nopara)>
<!ATTLIST image
  filename CDATA #REQUIRED>


<!ELEMENT person (name, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT version (listitem+)>
<!ATTLIST version
  name CDATA #REQUIRED
  unreleased CDATA 'false'>

=== axkg/terminatorX/website/download.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE section SYSTEM "./tX.dtd">
<section name='download'>
  <download>
    <index>
      <title>Available Downloads</title>
    </index>
    <current version='3.80' havebz2='yes' />
    <subsection>
      <title>Requirements</title>
      <para>terminatorX requires: 
      <itemizedlist>
        <listitem>
          <nopara>A Linux or FreeBSD system with the GNU C library
          installed.</nopara>
        </listitem>
        <listitem>
          <nopara>
          <link ref='http://www.xfree86.org'>XFree86</link> with DGA/DirectMouse
          support. DGA should be available in all XFree86 releases after 3.3,
          but 
          <bold>not every X-server provides DGA</bold>, so please check that
          your X-server has that feature. 
          <newline />
          <!--
<red>WARNING:
</red>
 XFree86 Version 4.0.0 has buggy
              DGA-Mouse support, please upgrade to Version 4.0.1 or above to
              be able to use terminatorX-->
</nopara>
        </listitem>
        <listitem>
          <nopara>The 
          <link ref='http://www.gtk.org'>Gimp Toolkit - gtk+</link> Version 2.0
          or above</nopara>
        </listitem>
        <listitem>
          <nopara>
          <link ref='http://www.ladspa.org'>LADSPA</link> The Linux Audio
          Developer's Simple Plugin API</nopara>
        </listitem>
        <listitem>
          <nopara>
          <link ref='http://www.libxml.org'>LibXML</link> which comes installed
          with most distributions</nopara>
        </listitem>
        <listitem>
          <nopara>terminatorX supports Steve Harris' 
          <link ref='http://plugin.org.uk/lrdf/'>liblrdf</link> which allows
          categorizing LADSPA plugins. Although terminatorX can be built
          without liblrdf support I strongly recommend installing it when you
          plan on using Steve Harris' wonderful 
          <link ref='http://plugin.org.uk/'>plugin collection</link> with
          terminatorX.</nopara>
        </listitem>
        <listitem>
          <nopara>terminatorX' MIDI interface is based on the ALSA sequencer
          API and therefor requires a working 
          <link ref='http://www.alsa-project.org'>ALSA</link> setup</nopara>
        </listitem>
        <listitem>
          <para>To enhance audiofile support I strongly recommend installing: 
          <itemizedlist>
            <listitem>
              <nopara>
              <link ref='http://www.68k.org/~michael/audiofile/'>
              libaudiofile</link> for loading wav, aiff and au files and 
              <link ref='http://sox.sourceforge.net'>sox</link> for
              pre-listening and loading of file formats not supported by
              libaudiofile.</nopara>
            </listitem>
            <listitem>
              <nopara>
              <link ref='http://www.xiph.org/ogg/vorbis/'>libvorbis</link> for
              loading of OGG Vorbis (.ogg) streams and 
              <link ref='http://www.xiph.org/ogg/vorbis/'>ogg123</link> for
              pre-listening to them.</nopara>
            </listitem>
            <listitem>
              <nopara>The 
              <link ref='http://www.mars.org/home/rob/proj/mpeg/'>
              mad</link> (MPEG Audio Decocder) library for loading mp3 streams
              and 
              <link ref='http://www.mpg123.de'>mpg123</link> or 
              <link ref='http://mpg321.sourceforge.net'>mpg321</link> for
              pre-listening of these.</nopara>
            </listitem>
          </itemizedlist>Note: Most of these libraries are included with
          current Linux distributions - so you might want to check your
          vendor's package list before building the libraries from
          source.</para>
        </listitem>
      </itemizedlist></para>
    </subsection>
    <subsection>
      <title>Current Version</title>
      <currentversion />
      <para>
      <link ref='http://www.debian.org'>Debian</link> users may prefer to
      install the 
      <link ref='http://packages.debian.org/unstable/sound/terminatorx.html'>
      terminatorX Debian package</link> via 
      <italic>apt-get</italic>.</para>
      <para>Mandrake users may be pleased to here that 
      <person>
        <name>Some</name>
        <email>email@email.de</email>
      </person> has created RPMs for their distribution 
      <link ref=''>here</link>.</para>
    </subsection>
    <subsection>
      <title>Old Sources</title>
      <tarfiles>
        <tar version='3.80' havebz2='yes' />
        <tar version='3.73' havebz2='yes' />
        <tar version='3.72' />
        <tar version='3.71' />
        <tar version='3.70' />
        <tar version='3.60' />
        <tar version='3.55' />
        <tar version='3.51' />
        <tar version='3.5' />
        <tar version='3.2' />
        <tar version='3.1' />
        <tar version='3.01' />
        <tar version='3.0' />
      </tarfiles>
    </subsection>
    <subsection>
      <title>Old RPMs</title>
      <rpmfiles>
        <!-- <rpm type="i386" version="3.80" rpmsubversion="1" distribution="Mandrake 9.1" note="no lilbrdf" ext="mdk"/> -->
<rpm rpmsubversion='1' version='3.80' type='i386' distribution='RH 8.0'
note='without liblrdf, ALSA, MIDI and libmad support' />
        <rpm rpmsubversion='1' version='3.73' type='i386' />
        <rpm rpmsubversion='1' version='3.72' type='i386' />
        <rpm rpmsubversion='2' version='3.71' type='i586' />
        <rpm rpmsubversion='1' version='3.70' type='i586' />
        <rpm rpmsubversion='2' version='3.60' type='i586' />
        <rpm rpmsubversion='2' version='3.71' type='sparc' />
        <rpm rpmsubversion='1' version='3.73' type='src' />
        <rpm rpmsubversion='1' version='3.72' type='src' />
        <rpm rpmsubversion='2' version='3.71' type='src' />
        <rpm rpmsubversion='1' version='3.70' type='src' />
        <rpm rpmsubversion='2' version='3.60' type='src' />
      </rpmfiles>
    </subsection>
    <subsection>
      <title>Historic Sources</title>
      <filelist>
        <file>terminatorX-V23.tar.gz</file>
        <file>terminatorX-V22.tar.gz</file>
      </filelist>
    </subsection>
    <subsection>
      <title>Samples</title>
      <para>I still have the "get you started"-samples 
      <file>scratch.wav</file> and 
      <file>beat.wav</file> available. If you have some audio files to scratch
      on but no beats (loops) lying around here is 
      <file>tX_beats.tar.bz2</file> which contains ten more beats I downloaded
      somewhere else - Sorry I don't remember where they're from - if you know
      please tell me so I can put some credits up here.</para>
      <para>If you want to have even more samples check out 
      <person>
        <name>Erik's</name>
        <email>e@osterman.com</email>
      </person>
      <bold>huge</bold> sample-archive 
      (<link ref='http://ftp.osterman.com/pub/music/samples'>http</link>/<link 
           ref='ftp://ftp.osterman.com/pub/music/samples'>ftp</link>).</para>
    </subsection>
  </download>
</section>

=== axkg/terminatorX/website/links.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE section SYSTEM "./tX.dtd">
<section name="links"> &db; <links>
    <index>
      <title>Links</title>
    </index>
    <subsection>
      <title>Linux Audio</title>
      <ilink>
        <banner filename="th_snd1.gif"/>
        <dblink id="linuxsound"/>
        <para>
          <person>
            <name>Dave Philips</name>
            <email>dlphilp@bright.net</email>
          </person> has not only written a <link ref="http://www.nostarch.com/lms.htm">book</link>
          on Linux audio software (that features terminatorX) - he is also maintaining the wonderful
            <dblink id="linuxsound"/>. IMHO it's the most complete collection of links to Linux
          audio projects and very well structured. </para>
      </ilink>
      <!--<ilink>
        <banner filename="rezound.png"/>
        <dblink id="rezound"/>
        <para>I don't really want to go into recommending other Linux software packages (as without
          maintenance such a list will always seem unfair), but I'll make an exception for the cool
            <dblink id="rezound"/> as I think it's the perfect tool to be used for terminatorX'
          soundfile editor option. It is specifically well-suited for creating and modifying loops. </para>
      </ilink>-->
      <ilink>
        <banner filename="freshmeat.gif"/>
        <dblink id="freshmeat"/>
        <para>I guess it's not necessary to introduce <dblink id="freshmeat"/>. If you want to be
          informed about new terminatorX releases you might want to subscribe to the terminatorX
            <link ref="http://freshmeat.net/projects/terminatorX">freshmeat project</link>.</para>
      </ilink>
      <ilink>
        <banner filename="lad.png"/>
        <dblink id="lad"/>
        <para>If you're working on a Linux audio project, you really should join the <dblink
            id="lad">Linux Audio Developers' mailing list</dblink>. If you just want to use Linux
          audio applications you might want to check out the <link
            ref="http://www.linuxdj.com/audio/lad/subscribelau.php3">Linux Audio Users' mailing
          list</link>. </para>
      </ilink>
    </subsection>
    <subsection>
      <title>Distributions</title>
      <para>Quite some OS distributions include terminatorX nowadays:</para>
      <ilink>
        <banner filename="debian.png"/>
        <dblink id="debian"/>
        <para>Simply the best and biggest. The machines I develop terminatorX on all run <dblink
          id="debian"/> (sid) and although <dblink id="debian"/> is not specifically targeted at
          multimedia users it features a whole lot of audio applications as it's just
          <bold>so</bold> big. You can find the terminatorX package <dblink
          id="testing">here</dblink> (testing) and <dblink id="unstable">here</dblink> (unstable). </para>
      </ilink>
      <ilink>
        <banner filename="dynebolic.png"/>
        <dblink id="dynebolic"/>
        <para>Based on <dblink id="debian"/>, <dblink id="dynebolic"/> is a multimedia Linux
          distribution that boots of a CD-ROM and doesn't require harddisk installation. So if you
          just want to test terminatorX without actually installing Linux (what you really should do
          :) <dblink id="dynebolic"/> might be an option. And it runs on XBOXen, too. </para>
      </ilink>
      <ilink>
        <banner filename="agnula.png"/>
        <dblink id="agnula"/>
        <para>
          <dblink id="agnula"/> is a project that aims to create a Linux distribution specifically
          targeted at musicians. They have released a beta release of their <dblink id="debian"/>
          based <link ref="http://www.demudi.org">DeMUDI</link> distribution. </para>
      </ilink>
      <ilink>
        <banner filename="ccrma.png"/>
        <dblink id="ccrma"/>
        <para>
          <dblink id="ccrma"/> provides up-to-date RPM packages of many audio applications for
          RedHat 7.2, 8.0 and 9 distributions. Their terminatorX package has much more features
          enabled than the one that I provide (as they provide RPMs for the dependencies that don't
          come with RedHat, too). </para>
      </ilink>
      <ilink>
        <banner filename="suse.png"/>
        <dblink id="suse"/>
        <para>Thanks to <person>
            <name>Matthias</name>
            <email>mana@suse.de</email>
          </person>, <dblink id="suse"/> provide a terminatorX <link
          ref="http://www.suse.de/us/private/products/suse_linux/i386/packages_personal/terminatorx.html">package</link>
          for quite some time now.</para>
      </ilink>
      <ilink>
        <banner filename="freebsd.png"/>
        <link ref="http://www.freebsd.org"/>
        <para>If you want to use terminatorX on your <dblink id="freebsd"/> box, you can use the
          official <link
            ref="http://www.FreeBSD.org/cgi/cvsweb.cgi/ports/audio/terminatorx">terminatorX port</link>.</para>
      </ilink>
    </subsection>
    <subsection>
      <title>terminatorX Coverage</title>
      <ilink>
        <banner filename="sonar.png"/>
        <dblink id="sonar"/>
        <para>The friendly people of <dblink id="sonar"/> invited me to do a terminatorX demo for
            <link ref="http://www.sonar.es/2003/eng/festival/rama.cfm">Sonarama</link> at the 2003
          Sonar festival (Friday 13th). </para>
      </ilink>
      <ilink>
        <banner filename="openjay.png"/>
        <dblink id="openjay"/>
        <para>
          <dblink id="openjay"/> is a website for open source DJs. <person>
            <name>J_Zar</name>
            <email>contact@openjay.org</email>
          </person> a very nice <link
          ref="http://www.openjay.org/modules.php?op=modload&amp;name=Sections&amp;file=index&amp;req=viewarticle&amp;artid=13&amp;page=1">review</link>
          on terminatorX. </para>
      </ilink>
      <ilink>
        <banner filename="neural.png"/>
        <dblink id="neural"/>
        <para>
          <dblink id="neural"/> is an online magazine for hacktivism, e-music and new media art.
          They have an Italian <link
          ref="http://www.neural.it/nnews/terminatorx.htm">introduction</link> on terminatorX.</para>
      </ilink>
      <ilink>
        <banner filename="or.png"/>
        <link ref="http://linux.oreillynet.com"/>
        <para>
          <person>
            <name>Dave</name>
            <email>dlphilp@bright.net</email>
          </person> wrote an introductory <link
          ref="http://linux.oreillynet.com/pub/a/linux/2001/02/02/ladspa.html">article</link> on
            <dblink id="ladspa"/> plugins and hosts that features terminatorX. </para>
      </ilink>
      <ilink>
        <banner filename="ct.png"/>
        <dblink id="ct"/>
        <para>The German computer magazine <dblink id="ct"/> once had terminatorX <link
          ref="http://www.heise.de/ct/shareware/default.shtml?prg=1845">included</link> on their
          freeware CDROM.</para>
      </ilink>
    </subsection>
    <!--
    <subsection>
      <title>Contributors (incomplete)</title>
      <ilink>
        <banner filename="kover.png"/>
        <dblink id="ladspa"/>
        <para/>
      </ilink>
    </subsection>
    -->
  </links>
</section>

=== axkg/terminatorX/website/aseqjoy.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE section SYSTEM "./tX.dtd">
<section name='aseqjoy'>
  &db;
  <aseqjoy>
    <para>
    <bold>aseqjoy</bold> is a 
    <italic>Joystick to ALSA MIDI Sequencer Converter</italic>. In fact it's a
    really tiny piece of software that turns a joystick into a MIDI controller
    for the 
    <dblink id='alsa'>ALSA</dblink> sequencer
    infrastructure. I mainly wrote it to test the new MIDI interface of
    terminatorX but then I thought it might be useful with other scenarios and
    applications, too.</para>
    <para>For a more detailed description on what it does and how to use it
    have a look the <dblink id='aseqjoy_man'>manpage</dblink>.</para>
    <para>If you want to test it yourself download the source: 
    <file>aseqjoy-0.0.1.tar.gz</file> (Sorry no
    binaries - but it's so small it only takes seconds to compile it yourself
    :) Compiling aseqjoy requires kernel and ALSA (asound library) headers to
    be installed.</para>
    <para>To compile and install it's really just the simple:</para>
    <para>
      <screen>tar xzf aseqjoy-0.0.1.tar.gz &amp;&amp; cd aseqjoy-0.0.1
      &amp;&amp; ./configure &amp;&amp; make &amp;&amp; make install</screen>
    </para>
    <para>To make full use of aseqjoy you might require jscal from the Vojtech
    Pavlik's 
    <link ref='http://atrey.karlin.mff.cuni.cz/%7Evojtech/joystick/'>joystick
    package</link> (to calibrate your joystick) and Robert Ham's 
    <link ref='http://pkl.net/%7Enode/alsa-patch-bay.html'>
    alsa-patch-bay</link> or aconnect from the 
    <dblink id='alsa'>alsa-utils</dblink> package to connect
    aseqjoy's MIDI output port to other input ports.</para>
    <para>aseqjoy is distributed under the terms of the 
    <dblink id='license'>GNU General Public License V2</dblink>.</para>
  </aseqjoy>
</section>

=== axkg/terminatorX/website/scratches.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE section SYSTEM "./tX.dtd"[ ]>
<section name='scratches'>
  &db;
  <scratches>
    <para>
    <bold>Yeah, Boy!</bold>(talking 
    <link ref='http://www.publicenemy.com/soldiers/flavor.php'>flavor</link>,
    here)</para>
    <para>Here are the current "users scratches". So you think these are not
    enough? Right, Ok, so do something about it! Read the text below if you
    want to send me what you created with terminatorX.</para>
    <scratchtable>
      <scratch>
        <mp3file>
          <file>asapien_scratch.mp3</file>
          <filesize>544kB</filesize>
        </mp3file>
        <author>
          <person>
            <name>Brian Redfern</name>
            <email>bredfern@calarts.edu</email>
          </person>
        </author>
        <comment>
          <nopara>This scratch is just a sample of a full 45min terminatorX
          set, which is available it at the 
          <link ref='http://asapien.org'>author's website</link>.</nopara>
          <tinycomment><nopara>The whole set is terminatorX plus an external reverb
          box.</nopara></tinycomment>
        </comment>
      </scratch>
      <scratch>
        <mp3file>
          <file>aint.mp3</file>
          <filesize>848kB</filesize>
        </mp3file>
        <author>
          <person>
            <name>Fernando S. Fabreti</name>
            <email>ffabreti@yahoo.com.br</email>
          </person>
        </author>
        <comment>
          <nopara>Aint no DJ but love to scratch!</nopara>
          <tinycomment>
            <nopara>created with his 
            <dblink id='turntables'>own turntable</dblink>.</nopara>
          </tinycomment>
        </comment>
      </scratch>
      <scratch>
        <mp3file>
          <file>jazzyscratch.mp3</file>
          <filesize>550kB</filesize>
        </mp3file>
        <author>
          <person>
            <name>Gregory A. Aluise</name>
            <email>aluise@udel.edu</email>
          </person>
          <tinycomment>
            <nopara>alias 
            <italic>DJ Giant 'G'</italic>of the 
            <link ref='http://farnkyboyz.virtualave.net'>
            FarnkyBoyz</link></nopara>
          </tinycomment>
        </author>
        <comment>
          <nopara>From the 
          <link ref='http://farnkyboyz.virtualave.net'>Farnky
          Boyz'</link> upcoming Album</nopara>
        </comment>
      </scratch>
      <scratch>
        <mp3file>
          <file>this.mp3</file>
          <filesize>1.4MB</filesize>
        </mp3file>
        <author>
          <person>
            <name>me</name>
            <email>alex@lisas.de</email>
          </person>
          <tinycomment>
            <nopara>
              <italic>again ;)</italic>
            </nopara>
          </tinycomment>
        </author>
        <comment>
          <nopara>my 3.5 demo</nopara>
        </comment>
      </scratch>
      <scratch>
        <mp3file>
          <file>cutitup.mp3</file>
          <filesize>780kB</filesize>
        </mp3file>
        <author>
          <person>
            <name>Gregory A. Aluise</name>
            <email>aluise@udel.edu</email>
          </person>
          <tinycomment>
            <nopara>alias 
            <italic>DJ Giant 'G'</italic>of the 
            <link ref='http://farnkyboyz.virtualave.net'>
            FarnkyBoyz</link></nopara>
          </tinycomment>
        </author>
        <comment>
          <nopara>Cut it up!</nopara>
          <tinycomment>
            <nopara>
            <italic>"Mixed in 15 min"</italic>- Wow!</nopara>
          </tinycomment>
        </comment>
      </scratch>
      <scratch>
        <mp3file>
          <file>stores.mp3</file>
          <filesize>1.3MB</filesize>
        </mp3file>
        <author>
          <person>
            <name>Tony Lambiris</name>
            <email>tonyl@telebot.com</email>
          </person>
        </author>
        <comment>
          <nopara>Stores Scratch</nopara>
        </comment>
      </scratch>
      <scratch>
        <mp3file>
          <file>hamsterscratch.mp3</file>
          <filesize>80kB</filesize>
        </mp3file>
        <author>
          <person>
            <name>Will Weiser</name>
            <email>kased811@ix.netcom.com</email>
          </person>
        </author>
        <comment>
          <nopara>Quick Hamster Scratch</nopara>
          <tinycomment>
            <nopara>www.hamsterdance.com</nopara>
          </tinycomment>
        </comment>
      </scratch>
      <scratch>
        <mp3file>
          <file>terminatorX.mp3</file>
          <filesize>470kB</filesize>
        </mp3file>
        <author>
          <person>
            <name>me</name>
            <email>alex@lisas.de</email>
          </person>
          <tinycomment>
            <nopara>again</nopara>
          </tinycomment>
        </author>
        <comment>
          <nopara>Messing Public Enemy</nopara>
          <tinycomment>
            <nopara>or: the tX title-scratch ;)</nopara>
          </tinycomment>
        </comment>
      </scratch>
      <scratch>
        <mp3file>
          <file>interrupt.mp3</file>
          <filesize>120kB</filesize>
        </mp3file>
        <author>
          <person>
            <name>John B. Fink</name>
            <email>jbfink@ogre.lib.muohio.edu</email>
          </person>
        </author>
        <comment>
          <nopara>Meat Beat Manifesto Meets Orson Wells</nopara>
        </comment>
      </scratch>
      <scratch>
        <mp3file>
          <file>linus.mp3</file>
          <filesize>200kB</filesize>
        </mp3file>
        <author>
          <person>
            <name>myself</name>
            <email>alex@lisas.de</email>
          </person>
        </author>
        <comment>
          <nopara>Linus pronounces Linux</nopara>
          <tinycomment>
            <nopara>from the silly sounds (see kernel archives)</nopara>
          </tinycomment>
        </comment>
      </scratch>
    </scratchtable>
    <para>In case 
    <bold>you</bold> want to get on the list above download terminatorX,
    practice and record your scratching. If you believe your skills are good
    enough 
    <link ref='mailto:alex@lisas.de'>mail</link> me your best scratch. Before
    you do so, please: 
    <itemizedlist>
      <listitem>
        <nopara>Ensure that it's not 
        <italic>too</italic> big.</nopara>
      </listitem>
      <listitem>
        <nopara>
        <italic>mp3</italic> or 
        <italic>ogg</italic> it. If you don't have an encoder go and get 
        <link ref='http://www.mp3dev.org/mp3//'>LAME</link>, 
        <link ref='http://bladeenc.mp3.no/'>BladeEnc</link> or 
        <link ref='http://www.xiph.org/ogg/vorbis/'>OggVorbis</link>.</nopara>
      </listitem>
    </itemizedlist></para>
  </scratches>
</section>
